# Generated by Django 3.1.6 on 2021-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_auto_20210205_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='description',
            field=models.CharField(default='default file description', max_length=1000),
        ),
    ]
