version: "3.3"
   
services:
    django:
        build: .
        container_name: django
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
        volumes:
            - .:/usr/src/app/
        ports:
            - "7000:8000"
        env_file: 
            - .env

        depends_on:
            - postgres-db
            - redis
    celery:
        build: .
        command: celery -A config.celery_app worker
        volumes:
            - .:/usr/src/app
        env_file: 
            - .env

        depends_on:
            - redis

    celery-beat:
        build: .
        command: celery -A config.celery_app beat
        volumes:
            - .:/usr/src/app
        env_file: 
            - .env

        depends_on:
            - django
            - celery
            - redis

    postgres-db:
        image: postgres:12.0-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data/
        env_file:
            - ./.env.db

    redis:
        image: "redis:alpine"
        
volumes:
    pgdata: