# Generated by Django 3.1.6 on 2021-02-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileapp', '0003_auto_20210205_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('file_messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fileapp.filemodel')),
            ],
        ),
    ]
